#!/bin/bash

function greenecho {
    echo "" && echo -e "\e[30;48;5;82m ✔ $1 \e[0m"
}
function orangeecho {
    echo "" && echo -e "\e[30;48;5;208m ⚠ $1 \e[0m"
}

# Get document root path
DOCUMENT_ROOT=$(drush status --fields=root --format=list)
THEME_PATH=$DOCUMENT_ROOT/themes/custom/$(drush status --fields=theme --format=list)


# Git repo root
cd $DOCUMENT_ROOT && cd ..

# Check for clean git working dir
if ! git diff --quiet; then
    orangeecho "Current repository is not clean, please review."
    exit 1
fi

# Backup database
greenecho "Backup local database"
drush sql-dump > /backups/DB_prod_`date +%Y-%m-%d_%H-%M-%S`.sql


# Fix local files permission
greenecho "Fix local files persmissions"
./scripts/fix_local_files_permissions

# Update sources
greenecho "Update sources"
git pull origin master

# Update dependencies
greenecho "Update dependencies (composer install --no-dev)"
composer install --no-dev --no-interaction

# Refresh cache
greenecho "Refresh caches"
drush cr

# Update database
greenecho "Update database"
drush updb -y

# Import new configuration
greenecho "Import configuration changes"
drush config-import -y

# Build theme assets
greenecho "Install npm dependencies"
composer theme-install --no-interaction

# Build theme assets
greenecho "Build theme assets"
composer theme-build --no-interaction

# Refresh cache
greenecho "Refresh caches"
drush cr
